#!/usr/bin/python

# main program
if __name__ == '__main__':
	from jail import update
	from jail import mount
	from jail import vhost
	from jail import mysql
	from jail import apache
	from jail import backup
	from jail import setup
	import argparse

	parser = argparse.ArgumentParser(description='Jail utilities')
	parser.add_argument('--update', action='store_true', help='Update jail directories')
	parser.add_argument('-M', '--mount-all', action='store_true', help='Mount all jail user directories')
	parser.add_argument('-U', '--umount-all', action='store_true', help='Umount all jail user directories')
	parser.add_argument('-m', '--mount', metavar='USER', help='Mount single user jail directories')
	parser.add_argument('-u', '--umount', metavar='USER', help='Umount single user jail directories')
	parser.add_argument('-l', '--list', action='store_true', help='List mounted user jails')
	parser.add_argument('--chroot-setup', action='store_true', help='Setup chroot environment with debootstrap')
	parser.add_argument('--chroot-upgrade', action='store_true', help='Update and upgrade chroot environment')
	parser.add_argument('--setup-groups', action='store_true', help='Create jail groups')
	args = parser.parse_args()
	if args.update:
		print 'UpdateGroup()'
		update.UpdateGroup()
	elif args.mount_all:
		print 'MountAll()'
		mount.MountAll()
	elif args.umount_all:
		print 'UmountAll()'
		mount.UmountAll()
	elif args.mount:
		print 'Mount(%s)' % args.mount
		mount.Mount(args.mount)
	elif args.umount:
		print 'Umount(%s)' % args.umount
		mount.Umount(args.umount)
	elif args.chroot_setup:
		print 'ChrootSetup()'
		setup.ChrootSetup()
	elif args.chroot_upgrade:
		print 'ChrootUpgrade()'
		setup.ChrootUpdate()
		setup.ChrootUpgrade()
	elif args.setup_groups:
		print 'SetupGroups()'
		setup.SetupGroups()
	elif args.list:
		print '\n'.join(mount.List())
