#!/usr/bin/python

# main program
if __name__ == '__main__':
	from jail import setup
	from jail import chroot
	import argparse

	parser = argparse.ArgumentParser(description='Jail utilities')
	parser.add_argument('--chroot-update', action='store_true', help='Setup chroot environment')
	parser.add_argument('--groups-setup', action='store_true', help='Create jail groups')
	args = parser.parse_args()
	if args.chroot_update:
		print 'ChrootUpdate()'
		chroot.MakeBase()
		chroot.CopyJailFiles(chroot.ChrootJailCopy)
	elif args.groups_setup:
		print 'GroupsSetup()'
		setup.GroupsSetup()
