#! /bin/sh
### BEGIN INIT INFO
# Provides:		jailfs
# Required-Start:
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Turn on/off jail filesystems for all users
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

. /lib/lsb/init-functions

umask 022

case "$1" in
  start)
	/usr/local/bin/jctl --update
	/usr/local/bin/jctl --mount-all
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	/usr/local/bin/jctl --umount-all
	;;
  *)   
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

:

